baseURL = "https://raghsonline.com"
href = ""
languageCode = "en-us"
title = "Blogs of Raghs"
#theme = "ananke" 
theme = "fuji"
#theme = "cupper-hugo-theme"
#theme = "hugo-coder"

[params]
  author = "Raghs" # You can also set author in post front matter individually
  #subTitle = "A minimal Hugo theme."
  defaultTheme = "dark" # default theme when first visit (auto|dark|light)

  # Word counter and read time indicator in post metadata
  showWordCounter = false
  showReadTime = true

  # Copyright
  copyrightStartYear = "2020"

  include_toc = false
  show_comments = true

  disqusShortname = "raghsonline"
  # If you want to use DisqusJS, please remember to set disqusJSApi to anything in your config.toml to load CSS.
  # disqusJSApi = "itsraghz" 
  disqus_identifier = "itsraghz"  
  

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # Enable user to embed HTML snippets in Markdown content
  [markup.highlight]
    codeFences = true  # Disable Hugo's code highlighter

  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4

[taxonomies]
  tag = "tags"

[menu]
  [[menu.nav]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Archives"
    url = "/archives/"
    weight = 2
  [[menu.nav]]
    name = "About"
    url = "/about/"
    weight = 3
  [[menu.nav]]
    name = "Search"
    url = "/search/"
    weight = 4
  [[menu.nav]]
    name = "RSS"
    url = "/index.xml"
    weight = 5

  [[menu.link]]
    name = "GitHub"
    url = "https://github.com/itsraghz"
    weight = 1
  [[menu.link]]
    name = "Twitter"
    url = "https://twitter.com/itsraghz"
    weight = 2
  [[menu.link]]
    name = "Linked In"
    url = "https://linkedin.com/in/itsraghz"
    weight = 3